name: PEP8

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Dependencies
        run: |
          python -m pip install --upgrade pipenv wheel
          pipenv install
      - name: Flake8
        run: |
          pipenv install flake8 
          pipenv run flake8
